### ISSUE TITLE
Telemetry?

### ISSUE THREAD

**Issue by calebcartwright** [swellaby/vsts-traffic-monitor#28]
Basically the same question for all our other distributable solutions, with the same discussion points as: https://github.com/swellaby/generator-swell/issues/111 

@traviskosarek elevating our discussion from Slack here for broader views.

My sense is that whatever we end up deciding can likely be applicable for all our VSTS extensions. Key questions again are around whether or not users should be able to opt out (via task config), I think they should be able to, and the last piece is what data point(s) we should collect.

Some basic usage info would be nice, and some error capture too (environment overview, like task version, node.js version, etc., _**no**_ user info)

**Comment by traviskosarek** [comment]
I agree with no user info. We aren't trying to be big brother, just get information on how our extensions are being used :)

Along the same lines, I think being able to opt out is important. In Slack we already mentioned using a checkbox within the task to control this. I think a pre-checked checkbox in a pre-collapsed accordion is best just from a "we can likely get the data we are looking for" and "it is not in a shared context with the task". That said, I am not sure if this can be thought of as "shady" because it would be initially hidden, but fully accessible. Thoughts?

**Comment by calebcartwright** [comment]
Agreed. Task configuration option to opt out. I think having a fully detailed set of documentation that outlines exactly what our telemetry is capturing, including links to capture/send points in the source code, could help mitigate some concern. The task source be open source (and also viewable post install via tfx cli tools) should hopefully help folks feel more concerned. 

In part, i'd really just like to get some info to help us support users when an issue arises

**Comment by calebcartwright** [comment]
Some proposed data points we could potentially gather/include in Telemetry Data:

- Task version
- VSTS Agent version
- OS? 
- Node (or Powershell for any PS impl tasks we have) version
- Task execution duration
- Error info (which needs more discussion)

**Comment by calebcartwright** [comment]
Some examples of data points that I believe we should _not_ include in telemetry data

- don't include the VSTS account name
- don't include IP address/hostname from env where task is executing
- don't include any sensitive task input values
- don't include any VSTS user data

**Comment by traviskosarek** [comment]
I agree with the above two comments of "proposed data points to capture" and the data points "we should not capture".

As far as "Error info", I think a pure stack trace could potentially add in some of the sensitive information we do not want to grab. This could be any of the "do not include" items or it could be some secret variables that are set in the build or within the vsts instance. Perhaps I am wrong?

I think here the safest bet is some specific error message/code that allows us to pinpoint where in the app this happened. That said, I would like more information if possible.

**Comment by calebcartwright** [comment]
Closing this as it no longer seems necessary, and the effort/cost of implementing significantly outweigh any potential benefits. 

The extension has been workin successfully for a long period of time, and the logging output should provide enough information for any users needing to report bugs. 

@traviskosarek - I think Telemetry and the points made here could still be relevant for the [git-mirror extension](https://github.com/swellaby/vsts-mirror-git-repository) however.
